const menu = [
  {
    id: 1,
    title: 'فول ',
    category: 'ترويقة',
    price: "250,000",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'فول مدمس',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'فول بالطحينة',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 4,
    title: 'فول بالخضار',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 5,
    title: 'فول باللبن',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 6,
    title: 'بليلة ',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 7,
    title: 'مسبحة ',
    category: 'ترويقة',
    price: '250,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 8,
    title: 'لبنة نعنع ثوم و خيار',
    category: 'ترويقة',
    price: '300,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 9,
    title: 'لبنة سادة ',
    category: 'ترويقة',
    price: '300,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 10,
    title: 'فتة لبن ',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 11,
    title: 'فتة طحينة  ',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 12,
    title: 'فتة قاورما ',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 13,
    title: 'فتة لحمة ',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 14,
    title: 'فتة مقادم ',
    category: 'ترويقة',
    price: 'X',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 15,
    title: 'فتة لسانات ',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 16,
    title: 'جبنة حلوم',
    category: 'ترويقة',
    price: '450,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 17,
    title: ' بيض مقلي',
    category: 'ترويقة',
    price: '300,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 18,
    title: ' بيض مسلوق',
    category: 'ترويقة',
    price: '300,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 19,
    title: ' بيض عيون',
    category: 'ترويقة',
    price: '300,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 20,
    title: ' بيض بندورة',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 21,
    title: ' بيض لحمة',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 22,
    title: ' بيض قاورما',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 23,
    title: ' بيض بطاطا',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 24,
    title: ' بيض بصل',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 25,
    title: ' بيض جبنة',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 26,
    title: ' بيض فطر',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 27,
    title: ' بيض سجق',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 28,
    title: ' بيض بالخضار',
    category: 'ترويقة',
    price: '400,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 29,
    title: ' بيض مقانق',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 30,
    title: '  حمص مع لحمة',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 31,
    title: '  حمص مع قاورما',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 32,
    title: '  سودة غنم نية  ',
    category: 'ترويقة',
    price: 'X',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 33,
    title: '   بيض بندورة بصل قاورما ',
    category: 'ترويقة',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 34,
    title: '   جاط خضرة',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 35,
    title: '    لبن و خيار  ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 36,
    title: '   تبولة     ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 37,
    title: '      فتوش  ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 38,
    title: '      سلطة الموسم  ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 39,
    title: '     سلطة جبنة   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 40,
    title: '      سلطة زعتر  ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 41,
    title: '     سلطة بقلة   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 42,
    title: '       سلطة روكا ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 43,
    title: '      سلطة شمندر  ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 44,
    title: '    بندورة مخمرة    ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 45,
    title: '     سلطة تونا   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 46,
    title: '     سلطة فطر   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 47,
    title: '     ارضي شوكي   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 48,
    title: '    سلطة الشيف    ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 49,
    title: '    سلطة نخاع    ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 50,
    title: '     سلطة لسانات   ',
    category: 'سلطات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 51,
    title:"حمص",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 52,
    title:"حمص بيروتي",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 53,
    title:"حمص مع مكسرات",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 54,
    title:"متبل",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 55,
    title:"راهب",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 56,
    title:"فول اخضر",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 57,
    title:"مدردرة",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 58,
    title:"مجدرة جنوبية",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 59,
    title:"مكدوس",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 60,
    title:"طاجن",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 61,
    title:"شنكليش",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 62,
    title:"لبنة نعنع و ثوم",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 63,
    title:"شكشوكة حرة",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 64,
    title:"ورق عنب",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 65,
    title:"هندبة بالزيت",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 66,
    title:"لوبية بالزيت",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 67,
    title:" محمرة",
    category: 'مقبلات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 68,
    title:"كفتة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 69,
    title:" شقف(عجل)",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 70,
    title:" شقف(غنم)",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 71,
    title:" طاووق",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 72,
    title:" مقانق",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 73,
    title:"سجق ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 74,
    title:" سودة مشوية",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 75,
    title:" سودة دجاج",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 76,
    title:"نخاع ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 77,
    title:" لسانات",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 77,
    title:" خشخاش",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 78,
    title:" هبرا مشوية",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 79,
    title:"كبة مشوية ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 80,
    title:" ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 81,
    title:"حمص مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 82,
    title:"متبل مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 83,
    title:" مجدرة مع خضرة",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 84,
    title:" مدردرة مع خضرة",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 85,
    title:"شنكليش مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 86,
    title:"لبنة مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 87,
    title:" لبنة مع مكدوس",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 88,
    title:"ورق عنب مع متبل ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 89,
    title:" بطاطا مقلية",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 90,
    title:"بطاطا حرة مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 91,
    title:"فول اخضر مع خضرة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 92,
    title:"   حلوم مع خضرة",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 93,
    title:"    اي اضافة ",
    category: 'سندويش',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 94,
    title:"   مشاوي مشكل عجل     ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 95,
    title:"   مشاوي مشكل غنم   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 96,
    title:"  عرايس لحمة    ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 97,
    title:"   لحم مشوي عجل   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 98,
    title:"   لحم مشوي غنم   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 99,
    title:"   كفتة مشوية   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 100,
    title:"   سودة مشوية   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 101,
    title:"   هبرا مشوية   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 102,
    title:"   كبة  مشوية   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 103,
    title:"   سجق مشوي   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 104,
    title:"   مقانق مشوية   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 105,
    title:"    خشخاش  ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 106,
    title:"   شيش طاووق   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 107,
    title:"    جوانح  ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 108,
    title:"   فروج على الفحم   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 109,
    title:"   نصف فروج على الفحم   ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 110,
    title:"   وجبة ابو حسن      ",
    category: 'مشاوي',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 111,
    title:"      سودة نية     ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 112,
    title:"       كفتة نية     ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 113,
    title:"        فتيلة نية    ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 114,
    title:"        ملسة نية    ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 115,
    title:"       مجرمشة     ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 116,
    title:"       كبة نية     ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 117,
    title:"      فراكة نية     ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 118,
    title:"    فراكة جنوبية       ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },

  {
    id: 119,
    title:"      نية مشكل      ",
    category: 'لحمة نية',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 120,
    title:"       مياه صغير      ",
    category: ' مرطبات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 121,
    title:"      مياه كبير       ",
    category: ' مرطبات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 122,
    title:"       مشروبات غازية      ",
    category: ' مرطبات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 123,
    title:"      شاي       ",
    category: ' مرطبات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 124,
    title:"       لبن عيران      ",
    category: ' مرطبات',
    price: '500,000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
];
export default menu;
